// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnswerVideoCall: typeof import('./src/components/video/AnswerVideoCall.vue')['default']
    Avatar: typeof import('./src/components/avatar/Avatar.vue')['default']
    ChatBubbles: typeof import('./src/components/chat/chatBubbles.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileUpload: typeof import('./src/components/fileUpload/FileUpload.vue')['default']
    FriendChat: typeof import('./src/components/chat/FriendChat.vue')['default']
    FriendGroups: typeof import('./src/components/FriendGroups.vue')['default']
    GroupChat: typeof import('./src/components/chat/GroupChat.vue')['default']
    IdentityCode: typeof import('./src/components/IdentityCode.vue')['default']
    MusicPlayer: typeof import('./src/components/ribbon/MusicPlayer.vue')['default']
    SearchUser: typeof import('./src/components/searchUser.vue')['default']
    SponsorVideoChat: typeof import('./src/components/video/SponsorVideoChat.vue')['default']
    UserInfo: typeof import('./src/components/ribbon/UserInfo.vue')['default']
    VideoChat: typeof import('./src/components/video/VideoChat.vue')['default']
    WeatherCard: typeof import('./src/components/ribbon/WeatherCard.vue')['default']
  }
}

export { }
