// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChatBubbles: typeof import('./src/components/chat/chatBubbles.vue')['default']
    DialougeList: typeof import('./src/components/DialougeList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBadge: typeof import('element-plus/es')['ElBadge'];
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    FriendChat: typeof import('./src/components/chat/FriendChat.vue')['default']
    FriendGroups: typeof import('./src/components/FriendGroups.vue')['default']
    GroupChat: typeof import('./src/components/chat/GroupChat.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MusicPlayer: typeof import('./src/components/ribbon/MusicPlayer.vue')['default']
    Ribbon: typeof import('./src/components/ribbon/Ribbon.vue')['default']
    WeatherCard: typeof import('./src/components/ribbon/WeatherCard.vue')['default']
  }
}

export { }
